services:
  app:
    image: vethsothi/library-app:v1.1.4
    container_name: library_app
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: ${APP_KEY}
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    container_name: library_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always

  node:
    image: node:20-alpine
    container_name: library_node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    depends_on:
      - app

  mysql:
    image: mysql/mysql-server:8.0
    container_name: library_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
